package io.ilot.plol.model;

public class ConstantsLiveOdds
{
    // E_ for element, A_ for attribute, V_ for values
    public static String
            E_BETRADARLIVEODDS = "BetradarLiveOdds",
            E_MESSAGE = "Message",
            E_MATCH = "Match" ,
            E_ODDS = "Odds" ,
            E_ODDSFIELD = "OddsField" ,
            E_SCORE = "Score" ,
            E_MATCHINFO = "MatchInfo" ,
            E_CARD = "Card" ,
            E_DATEOFMATCH = "DateOfMatch" ,
            E_SPORT = "Sport" ,
            E_CATEGORY = "Category" ,
            E_TOURNAMENT = "Tournament" ,
            E_HOMETEAM = "HomeTeam" ,
            E_AWAYTEAM = "AwayTeam" ,
            E_TVCHANNELS = "TvChannels" ,
            E_TVCHANNEL = "TvChannel" ,
            E_EXTRAINFO = "ExtraInfo" ,
            E_INFO = "Info" ,
            E_TRANSLATION = "Translation" ,

    A_BETRADARLIVEODDS_TIMESTAMP = "timestamp" ,
            A_BETRADARLIVEODDS_STATUS = "status" ,
            A_BETRADARLIVEODDS_REPLYNR = "replynr" ,
            A_BETRADARLIVEODDS_REPLYTYPE = "replytype" ,
            A_BETRADARLIVEODDS_TIME = "time" ,
            A_BETRADARLIVEODDS_TYPE = "type" ,
            A_BETRADARLIVEODDS_XMLNS = "xmlns" ,
            A_BETRADARLIVEODDS_ENDTIME = "endtime" ,
            A_BETRADARLIVEODDS_STARTTIME = "starttime" ,

    A_MATCH_ACTIVE = "active" ,
            A_MATCH_BOOKED = "booked" ,
            A_MATCH_BETSTATUS = "betstatus" ,
            A_MATCH_EARLYBETSTATUS = "earlybetstatus" ,
            A_MATCH_CLEAREDSCORE = "clearedscore" ,
            A_MATCH_CORNERSAWAY = "cornersaway" ,
            A_MATCH_CORNERSHOME = "cornershome" ,
            A_MATCH_MATCHID = "matchid" ,
            A_MATCH_MATCHTIME = "matchtime" ,
            A_MATCH_MSGNR = "msgnr" ,
            A_MATCH_REDCARDSAWAY = "redcardsaway" ,
            A_MATCH_REDCARDSHOME = "redcardshome" ,
            A_MATCH_SUSPENDHOME = "suspendHome",
            A_MATCH_SUSPENDAWAY = "suspendAway",
            A_MATCH_SCORE = "score" ,
            A_MATCH_SETSCORES = "setscores" ,
            A_MATCH_SETSCORE1 = "setscore1" ,
            A_MATCH_SETSCORE2 = "setscore2" ,
            A_MATCH_SETSCORE3 = "setscore3" ,
            A_MATCH_SETSCORE4 = "setscore4" ,
            A_MATCH_SETSCORE5 = "setscore5" ,
            A_MATCH_SETSCORE6 = "setscore6" ,
            A_MATCH_SETSCORE7 = "setscore7" ,
            A_MATCH_SETSCORE8 = "setscore8" ,
            A_MATCH_SETSCORE9 = "setscore9" ,
            A_MATCH_SETSCORE10 = "setscore10" ,
            A_MATCH_REMAINING_TIME = "remaining_time" ,
            A_MATCH_REMAINING_TIME_IN_PERIOD = "remaining_time_in_period" ,
            A_MATCH_CLOCK_STOPPED = "clock_stopped" ,
            A_MATCH_GAMESCORE = "gamescore" ,
            A_MATCH_TIEBREAK = "tiebreak" ,
            A_MATCH_SERVER = "server" ,
            A_MATCH_STATUS = "status" ,
            A_MATCH_YELLOWCARDSAWAY = "yellowcardsaway" ,
            A_MATCH_YELLOWCARDSHOME = "yellowcardshome" ,
            A_MATCH_YELLOWREDCARDSAWAY = "yellowredcardsaway" ,
            A_MATCH_YELLOWREDCARDSHOME = "yellowredcardshome" ,
            A_MATCH_AWAYBATTER = "awaybatter" ,
            A_MATCH_HOMEBATTER = "homebatter" ,
            A_MATCH_BALLS = "balls" ,
            A_MATCH_BASES = "bases" ,
            A_MATCH_OUTS = "outs" ,
            A_MATCH_STRIKES = "strikes",
            A_MATCH_POSITION = "position",
            A_MATCH_POSSESSION = "possession",
            A_MATCH_TRY = "try",
            A_MATCH_YARDS = "yards",
            A_MATCH_EXPEDITE = "expedite",

    A_ODDS_ID = "id",
            A_ODDS_MOSTBALANCED = "mostbalanced" ,
            A_ODDS_SPECIALODDSVALUE = "specialoddsvalue" ,
            A_ODDS_SUBTYPE = "subtype" ,
            A_ODDS_TYPE = "type" ,
            A_ODDS_TYPEID = "typeid" ,
            A_ODDS_ACTIVE = "active" ,
            A_ODDS_CHANGED = "changed" ,
            A_ODDS_COMBINATION = "combination" ,
            A_ODDS_FREETEXT = "freetext" ,

    A_ODDSFIELD_ACTIVE = "active" ,
            A_ODDSFIELD_TYPE = "type" ,
            A_ODDSFIELD_OUTCOME = "outcome" ,
            A_ODDSFIELD_VOIDFACTOR = "voidfactor" ,


    A_CARD_ID = "id" ,
            A_CARD_PLAYER = "player" ,
            A_CARD_TEAM = "team" ,
            A_CARD_TIME = "time" ,
            A_CARD_TYPE = "type" ,
            A_CARD_CANCELED = "canceled" ,

    A_SCORE_AWAY = "away" ,
            A_SCORE_HOME = "home" ,
            A_SCORE_ID = "id" ,
            A_SCORE_PLAYER = "player" ,
            A_SCORE_SCORINGTEAM = "scoringteam" ,
            A_SCORE_CANCELED = "canceled" ,
            A_SCORE_TIME = "time" ,
            A_SCORE_TYPE = "type" ,

    A_SPORT_ID = "id" ,

    A_CATEGORY_ID = "id" ,

    A_TOURNAMENT_ID = "id" ,

    A_HOMETEAM_ID = "id" ,
            A_HOMETEAM_UNIQUEID = "uniqueid" ,

    A_AWAYTEAM_ID = "id" ,
            A_AWAYTEAM_UNIQUEID = "uniqueid",

    A_INFO_TYPE = "type",
            V_INFO_TYPE_NUM_OF_SETS = "NumberOfSets"
                    ;
}
